spring:
    application:
        name: medilabo-notes
    data:
        mongodb:
            host: ${MONGODB_HOST:localhost}
            port: ${MONGODB_PORT:27017}
            database: ${MONGODB_DATABASE:notes}

server:
    port: 8083




