logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
server:
  port: 8080

spring:
  application:
    name: medilabo-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: medilabo-front
          uri: ${FRONT_URL:http://localhost:8082}
          predicates:
            - Path=/patients/**,/notes/**,/css/**
        - id: medilabo-patient
          uri: ${PATIENT_URL:http://localhost:8081}
          predicates:
            - Path=/api/patients/**
        - id: medilabo-notes
          uri: ${NOTES_URL:http://localhost:8083}
          predicates:
            - Path=/api/notes/**
        - id: medilabo-diabetes-assessment
          uri: ${ASSESSMENT_URL:http://localhost:8084}
          predicates:
            - Path=/assessment/**
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  security:
    enabled: false
