spring:
  application:
    name: medilabo-diabetes-assessment
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/medilabo}
server:
  port: 8084

patient:
  service:
    url: ${PATIENT_SERVICE_URL:http://localhost:8081/api/patients}
note:
  service:
    url: ${NOTE_SERVICE_URL:http://localhost:8083/api/notes}

