spring:
  application:
    name: medilabo-front

server:
  port: 8082

patient:
  client:
    url: http://localhost:8080/api/patients

note:
  client:
    url: http://localhost:8080/api/notes

assessment:
  client:
    url: http://localhost:8080/assessment
